### ISSUE TITLE
No SNI Support ?

### ISSUE THREAD

**Issue by Golbark** [android-async-http/android-async-http#991] opened 2015-10-11 06:59 UTC
When we try to access an API on a subdomain we get the following error : 

```
hostname in certificate didn't match: <sub.domain.be> != <domain.be> OR <domain.be> OR <www.domain.be>
```

SSLlabs gives compatibility with all browsers except the ones that do not support SNI.

However, we are using the latest version of the library (1.4.9) which is supposed to support SNI.

**Comment by Golbark** [comment] 2015-10-11 07:08
I see that you use in the library gradle build file :
```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_6
        targetCompatibility JavaVersion.VERSION_1_6
    }
```
Can the issue be related with the fact that SNI is supported in the Java SSL Library only on 1.7 version and above ?

**Comment by smarek** [comment] 2015-10-11 12:08
Well, pitty, thanks for testing that. Unsafe workaround would be to use ALLOW_ALL_HOSTNAME_VERIFIER which disables cert validation, which is of course not a correct way.

I've tried to enable 1.7 SDK compilation in both underlying HttpClient library and in AAH library, both unsuccessfull (meaning even when compiling against 1.7 SDK SNI support doesn't appear).

I've added 1.7 support to 4.4.1 version (under 4.4.1.2 future release mark), but that didn't make any difference.

Neither did that trick changing the compile runtime on 4.3.6 

Could you please try workout the solution which is proposed here? https://github.com/owncloud/android/pull/321/files

**Comment by Nabellaleen** [comment] 2015-12-04 14:45
Hi,

Any news about the 1.4.9.1 and, in particular, this issue ?

Our production servers are using SNI, so we're waiting for this update to launch our app' in production. So I would like to have an approximative E.T.A. to decide if we're waiting a few more days/weeks or if we take the time to replace the lib' by another one.

**Comment by kamilwlf** [comment] 2016-01-12 06:27
any news?

**Comment by jaumard** [comment] 2016-02-26 11:47
I have same problem here SNI not working with 1.4.9 :( my new company use SNI on there production servers so I need this feature now :/ how far is the 1.4.9.1 ?

**Comment by kamilwlf** [comment] 2016-02-26 11:51
I switched to okHttp and all problems were gone

**Comment by saeed-rz** [comment] 2019-07-17 18:51
is there any server for testing SNI?

**Comment by smarek** [comment] 2019-07-17 20:31
@saeed-rz well any basically, you can use www.google.com, see basic output from util

```
gnutls-cli --disable-sni www.google.com
Processed 22 CA certificate(s).
Resolving 'www.google.com:443'...
Connecting to '172.217.23.228:443'...
- Certificate type: X.509
- Got a certificate list of 1 certificates.
- Certificate[0] info:
 - subject `CN=invalid2.invalid,OU=No SNI provided\; please fix your client.', issuer `CN=invalid2.invalid,OU=No SNI provided\; please fix your client.', serial 0x0090768918e93393a0, RSA key 2048 bits, signed using RSA-SHA256, activated `2015-01-01 00:00:00 UTC', expires `2030-01-01 00:00:00 UTC', pin-sha256="j4i4cwAEhF/BFKbkqi8WZWur4bMvr2/EbovM0ku1FNc="
	Public Key ID:
		sha1:183151b78e084135af782d70db9efc747b8d5d88
		sha256:8f88b8730004845fc114a6e4aa2f16656babe1b32faf6fc46e8bccd24bb514d7
	Public Key PIN:
		pin-sha256:j4i4cwAEhF/BFKbkqi8WZWur4bMvr2/EbovM0ku1FNc=

- Status: The certificate is NOT trusted. The certificate issuer is unknown. The name in the certificate does not match the expected. 
*** PKI verification of server certificate failed...
*** Fatal error: Error in the certificate.
```

**Comment by saeed-rz** [comment] 2019-07-18 11:47
I have checked with [www.google.com](http://www.google.com/),  and its work fine!

**Comment by smarek** [comment] 2019-07-18 19:15
@saeed-rz relevant implementation note is here https://github.com/android-async-http/android-async-http/issues/1201#issue-174376434

Also to make sure it really works, we have to test with oldest supported version, AVD should be fine imho

**Comment by saeed-rz** [comment] 2019-08-02 19:55
I have checked the current version with services behind the Cloudflare and it seems ok. 
before the test, I try to scan service with "https://www.ssllabs.com/ssltest", and the report says: services work only in browsers with SNI support.
I think this issue fixed.

**Comment by smarek** [comment] 2019-08-05 10:01
Thank you, I'm closing the issue, but leaving the discussion open, if the problem is not fixed for everyone.

For all watching this ticket, please update to latest version of library, 1.4.10 ( see instructions here https://github.com/android-async-http/android-async-http#maven ), if the issue persists in your case, please comment here. Thank you!

**Closed by smarek** 2019-08-05 10:01 UTC
Labels: feature-request, moderate
