### ISSUE TITLE
Fatal Exception: java.lang.AssertionError

### ISSUE THREAD

**Issue by nextflex** [android-async-http/android-async-http#1325] opened 2019-10-24 08:32 UTC
```
Fatal Exception: java.lang.AssertionError: use looper thread, must call Looper.prepare() first!
       at com.loopj.android.http.Utils.asserts(Utils.java:39)
       at com.loopj.android.http.AsyncHttpResponseHandler.<init>(AsyncHttpResponseHandler.java:137)
       at com.loopj.android.http.AsyncHttpResponseHandler.<init>(AsyncHttpResponseHandler.java:122)
       at com.loopj.android.http.AsyncHttpResponseHandler.<init>(AsyncHttpResponseHandler.java:110)
       at com.loopj.android.http.TextHttpResponseHandler.<init>(TextHttpResponseHandler.java:73)
       at com.loopj.android.http.JsonHttpResponseHandler.<init>(JsonHttpResponseHandler.java:48)
```

Example Code:
```
AsyncHttpClient client = new AsyncHttpClient();
 RequestHandle requestHandle = client.post(context, url, param, new JsonHttpResponseHandler() {
            @Override
            public void onSuccess(int statusCode, Header[] headers, JSONObject response) {...}
})
```

Called inside FirebaseMessagingService -> onNewToken(token)

Version: 1.4.10
API Level: 5 - 9

**Comment by smarek** [comment] 2019-10-24 13:32
Seems to me that you're using Async http-client where no looper context is available, and the error is pretty self-explanatory to me, use `Looper.prepare();` before you use `client.post(` or any HTTP method interface

Let me know if that works for you

**Comment by smarek** [comment] 2019-10-30 08:54
Closing this as duplicate of #1324, please continue with your findings there.

**Closed by smarek** 2019-10-30 08:54 UTC
