### ISSUE TITLE
Upload large file issue

### ISSUE THREAD

**Issue by coolwd10** [android-async-http/android-async-http#1205] opened 2016-09-09 12:28 UTC
File size 174.67 Mb
File type Zip
Method Post
file===zipfile
```
RequestParams params = new RequestParams();
        if (file != null && file.exists())
            params.put("Db_file", new FileInputStream(file));


    //set the content-type multipart/form-data
    params.setForceMultipartEntityContentType(true);
```

Throwing OutOfMemoryError "Failed to allocate a 134209900 byte allocation with 8388608 free bytes and 109MB until OOM"

**Comment by smarek** [comment] 2019-07-21 13:16
Closing this as duplicate of #127

**Closed by smarek** 2019-07-21 13:16 UTC
